version: '3'

services:
  frontend:
    build: ./front
    restart: always
    ports:
      - 3333:3000
    env_file:
      - ./front/.env
  backend:
    build: ./back
    restart: always
    ports:
      - 5555:5000
    depends_on:
      - mongo
    env_file:
      - ./back/.env
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongodb
    environment:
      DATABASE_USER: test
      DATABASE_PASSWORD: test
