
export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_SET_LOGGED_IN = 'AUTH_SET_LOGGED_IN';

export const AUTH_GET_USER_PENDING = 'AUTH_GET_USER_PENDING'
export const AUTH_GET_USER_FULL_FILLED = 'AUTH_GET_USER_FULL_FILLED'
export const AUTH_GET_USER_REJECTED = 'AUTH_GET_USER_REJECTED'
